### ISSUE TITLE
Feature request:  Ability to copy current page URL to clipboard

### ISSUE THREAD

**Issue by mitchmeister** [christianpatrick/electron-zoho_crm#5]
Would it be possible to add ability to copy the URL of the current Zoho CRM page to the clipboard, possibly via a "Copy link" menu item under "Edit"

**Comment by christianpatrick** [comment]
Hi @mitchmeister!

I'll be happy to add that in.

**Comment by christianpatrick** [comment]
Thanks for your patience on this one! Version 1.1.6 now has the ability to right-click on links and copy them. You can download it [here](https://github.com/christianpatrick/electron-zoho_crm/releases/tag/v1.1.6).
